from django import forms
class T_company(forms.Form):
    Company_id  = forms.CharField(required=True,max_length=200)
Company_name = forms.CharField(required=True,max_length=50)
Company_email = forms.CharField(required=True,max_length=100)
Company_tel =forms.CharField(required=True,max_length=50)
Company_postcode = forms.CharField(required=True,max_length=50) 
Company_homepage = forms.CharField(required=True)
Manager_name = forms.CharField(required=True)
Manager_tel = forms.CharField(required=True)
Manager_email = forms.CharField(required=True)
Project_name = forms.CharField(required=True)
Neededskill = forms.CharField(required=True)
Otherskill = forms.CharField(required=True)
Company_address = forms.CharField(required=True)
Period = forms.CharField(required=True)
Job_detail = forms.CharField(required=True)
Needed_member = forms.CharField(required=True)
Unit_price = forms.CharField(required=True)
Note = forms.CharField(required=True)